# Discovery server port
ds:
  port: 8888

# Postgresql port
ps:
  port: 5432

spring:
  datasource:
    url: jdbc:postgresql://postgres:${ps.port}/microservices-exercises
    username: postgres
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# docker customer service port
server:
  port: 8081

# Docker discovery server client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:${ds.port}/eureka/
    registerWithEureka: true
    fetchRegistry: true