# Discovery server port
ds:
  port: 8888

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/customer-service**
          - id: product-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/product-service**
          - id: order-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/v1/order-service**
          - id: eureka
            uri: http://localhost:${ds.port}
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
          - id: eureka-static
            uri: http://localhost:${ds.port}
            predicates:
              - Path=/eureka/**

# server own port gateway server port
server:
  port: 8080

# Discovery server client settings,
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${ds.port}/eureka/
    registerWithEureka: true
    fetchRegistry: true