# Discovery server port
ds:
  port: 8888



spring:
  data:
    mongodb:
      host: mongo
      authentication-database: admin
      username: root
      password: root
      database: notification
      port: 27017

# docker notification service port
server:
  port: 8085

# Docker discovery server client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:${ds.port}/eureka/
    registerWithEureka: true
    fetchRegistry: true