# Discovery server port
ds:
  port: 8888
ps:
  port: 5432

spring:
  datasource:
    url: jdbc:postgresql://localhost:${ps.port}/microservices.product-service
    username: postgres
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# product service local port
server:
  port: 8082

# discovery server client configurations
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${ds.port}/eureka/
    registerWithEureka: true
    fetchRegistry: true